server:
  port: 8888
  servlet:
    context-path: /demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.0.104
    port: 6379
    password: 123456
mybatis:
  type-aliases-package: com.example.demo.entries
  mapper-locations: classpath:/com/example/demo/mapper/*.xml